# OpenJDK 21 기반 이미지 사용
FROM eclipse-temurin:21-jdk


ARG EUREKA_USERNAME=${EUREKA_USERNAME}
ARG EUREKA_PASSWORD=${EUREKA_PASSWORD}
ARG JWT_SECRET=${JWT_SECRET}
ARG GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ARG GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ARG NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
ARG NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
ARG KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
ARG KAKAO_ADMIN_KEY=${KAKAO_ADMIN_KEY}

ENV EUREKA_USERNAME=${EUREKA_USERNAME}
ENV EUREKA_PASSWORD=${EUREKA_PASSWORD}
ENV JWT_SECRET=${JWT_SECRET}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
ENV NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
ENV KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
ENV KAKAO_ADMIN_KEY=${KAKAO_ADMIN_KEY}


WORKDIR /app

# JAR 파일 복사
COPY target/eventor-auth-0.0.1-SNAPSHOT.jar eventor-auth.jar

# 애플리케이션 실행
ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "eventor-auth.jar"]