spring:
  # 캐시 활성화
  thymeleaf:
    cache: true

  data:
    redis:
      host: redis

eureka:
  client:
    service-url:
      defaultZone: http://root:1q2w3e4r!@eventor-eureka:8761/eureka
  instance:
    prefer-ip-address: true

feignClient:
  url: eventor-gateway:8090