spring:
  # 캐시 활성화
  thymeleaf:
    cache: true

  data:
    redis:
      host: redis
      password: ${REDIS_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@eventor-eureka:8761/eureka
  instance:
    prefer-ip-address: true

feignClient:
  url: eventor-gateway:8090