spring:
  # 캐시 비활성화
  thymeleaf:
    cache: false

  data:
    redis:
      host: localhost

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka
  instance:
    prefer-ip-address: true


feignClient:
  url: localhost:8090

#logging:
#  level:
#    org.springframework.web: DEBUG
