server:
  port: 8070

spring:
  application:
    name: "eventor-auth"

  profiles:
    active: dev

  data:
    redis:
      password: ${REDIS_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}
    access-token:
      expires-in: 600000
    refresh-token:
      expires-in: 86400000

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://www.eventor.store/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: email profile


          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: https://www.eventor.store/oauth2/code/naver
            scope: name, email

          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: https://www.eventor.store/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            admin-key: ${KAKAO_ADMIN_KEY}

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://accounts.googleapis.com/oauth2/v3/userinfo
            user-name-attribute:

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


logging:
  file:
    path: ./logs

  level:
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR

# 비밀번호 변경